version: "3.2"
services:
  php:
    build:
      context: .
      dockerfile: Dockerfile.local
    command: "/bin/bash -c 'cp php.ini $PHP_INI_DIR/php.ini && chown -R www-data:www-data tmp && php-fpm'"
    #php composer.phar
    working_dir: /var/www
    volumes:
      - .:/var/www
      - ./conf.d/:/etc/nginx/conf.d/
    networks:
      tinyfam_network:
        aliases:
          - php
  web:
    image: nginx:latest
    ports:
      - "8080:80"
    links:
      - php
    volumes:
      - .:/var/www
      - ./conf.d/default.conf:/etc/nginx/conf.d/default.conf
    networks:
      tinyfam_network:
    links:
      - php
    depends_on:
      - php
  composer:
    image: composer:1.9
    command: ["composer", "install"]
    volumes:
      - .:/app
  mysql:
    image: mysql:5.7
    environment:
      - MYSQL_DATABASE=mysql_database
      - MYSQL_ROOT_PASSWORD=mysql_strong_password
    networks:
      tinyfam_network:

networks:
  tinyfam_network: